source 'https://www.rubygems.org'
gem 'appium_console'
gem 'appium_lib', '~> 12.0', '>= 12.0.1'
gem 'cucumber'
gem 'eventmachine', '1.2.7', git: 'https://github.com/eventmachine/eventmachine.git', tag: 'v1.2.7'
gem 'rubocop', '~> 0.64.0'
